version: '3.8'

services:

  simple-web-service:
    image: devopsdockeruh/simple-web-service
    ports:
      - 8080:8080
    build: .
    command: -p 8080:8080 devopsdockeruh/simple-web-service server
    container_name: simple-web2
