version: '3.8'

services:
  proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:13.2-alpine
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis
    restart: unless-stopped
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
    build: ../material-applications/example-backend-fixed
    depends_on:
      - cache
      - db
    container_name: backend
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    build: ../material-applications/example-frontend-fixed
    container_name: frontend

volumes:
  database:

